# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd619507ea87fafbcae1e626ce0eb02e5ad9ab375fe5b1e8e99b78a8b2f74743f8602d8b108051d7797edebf106386ec3259e950d61cc795e7cb396944858177

test:
  secret_key_base: 247088fdd88149e8656274256aa5f4e1ffaf1e675be5dff225540d8d3d33e8a3fab810fad74b2f1ec22cd2fe05fc6e6124b68072b0372abf0f7881f8cf4d2a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
